### ISSUE TITLE
Dangling node in yaml file causes difficult error message

### ISSUE THREAD

**Issue by berland** [equinor/xtgeoapp-grd3dmaps#26]
Attempt at reconstruction (taken from an example, not the real user config):
```
input:
  eclroot: ../xtgeo-testdata/3dgrids/reek/REEK
  grid: $eclroot.EGRID

  # alternative approach to read a variables and dates:
  properties:
    -
      name: PORO
      source: $eclroot.INIT
    -
      name: SWAT
      source: $eclroot.UNRST
      dates: !include_from tests/yaml/global_config3a.yml::global.DATES
      diffdates: !include_from tests/yaml/global_config3a.yml::global.DIFFDATES
    -
#      name: PRESSURE
#      source: $eclroot.UNRST
#      dates: !include_from tests/yaml/global_config3a.yml::global.DATES
#      diffdates: !include_from tests/yaml/global_config3a.yml::global.DIFFDATES
``` 

The dangling dash `-` causes the error `TypeError: argument of type 'NoneType' is not iterable` from line 242 in `_configparser.py` which does ` if 'name' not in prop `
